# Generated by Django 5.1.1 on 2024-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=52)),
                ('description', models.TextField(max_length=252)),
                ('status', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField()),
                ('task_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
    ]
