# Generated by Django 4.2.16 on 2024-10-11 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=52)),
                ('description', models.TextField(max_length=252)),
                ('status', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
                ('reminder_time', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('complexity', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very hard'), (5, 'Impossible')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
